

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=Mazebank981$#1
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    restart: always

  backend:
    image: api
    build:
      context: ../API
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    restart: always
    depends_on:
      - database

  frontend:
    image: front
    build:
      context: ../Client
      dockerfile: Dockerfile
    volumes:
      - ../Client/build:/usr/share/nginx/html
    restart: always

  proxy:
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:81"
    depends_on:
      - backend
      - frontend
    restart: always

